SchedulerActivityTest/SimListActivityTest: fix ShadowSubscriptionManager.setAvailableSubscriptionInfos usages
java.lang.IllegalStateException: Looper thread that has died due to an uncaught exception
	at org.robolectric.shadows.ShadowPausedMessageQueue.checkQueueState(ShadowPausedMessageQueue.java:409)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:697)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:104)
	at org.robolectric.shadows.ShadowPausedLooper.idleFor(ShadowPausedLooper.java:113)
	at org.robolectric.shadows.ShadowLooper.idleFor(ShadowLooper.java:223)
	at org.robolectric.shadows.ShadowPausedLooper.runToNextTask(ShadowPausedLooper.java:194)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$Activity$test should debounce subscription change events when sent in bursts$1.invoke(SchedulerActivityTest.kt:242)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$Activity$test should debounce subscription change events when sent in bursts$1.invoke(SchedulerActivityTest.kt:227)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTestKt.onActivity(SchedulerActivityTest.kt:3894)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTestKt.onActivity$default(SchedulerActivityTest.kt:3761)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$Activity.test should debounce subscription change events when sent in bursts(SchedulerActivityTest.kt:227)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluateSafely(JUnitSessionStore.java:55)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluate(JUnitSessionStore.java:43)
	at com.github.takahirom.roborazzi.RoborazziRule$runTest$evaluate$1.invoke(RoborazziRule.kt:208)
	at com.github.takahirom.roborazzi.RoborazziRule$runTest$evaluate$1.invoke(RoborazziRule.kt:203)
	at com.github.takahirom.roborazzi.RoborazziRule.runTest(RoborazziRule.kt:238)
	at com.github.takahirom.roborazzi.RoborazziRule.access$runTest(RoborazziRule.kt:27)
	at com.github.takahirom.roborazzi.RoborazziRule$apply$1.evaluate(RoborazziRule.kt:186)
	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:108)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:502)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "android.telephony.SubscriptionInfo.getGroupUuid()" because "info" is null
	at android.telephony.SubscriptionManager.getSelectableSubscriptionInfoList(SubscriptionManager.java:3912)
	at com.github.iusmac.sevensim.telephony.SubscriptionList.<init>(SubscriptionList.java:21)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy$1.<init>(SubscriptionsImplLegacy.java:90)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy.iterator(SubscriptionsImplLegacy.java:90)
	at com.github.iusmac.sevensim.telephony.Subscriptions.getSubscription(Subscriptions.java:178)
	at com.github.iusmac.sevensim.telephony.Subscriptions.getSubscriptionForSubId(Subscriptions.java:195)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivity.lambda$onSubscriptionsChanged$3(SchedulerActivity.java:142)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowPausedLooper$LooperReflector$$Reflector4.loop(Unknown Source)
	at org.robolectric.shadows.ShadowPausedLooper.loop(ShadowPausedLooper.java:472)
	at android.os.Looper.loop(Looper.java)
	at android.os.HandlerThread.run(HandlerThread.java:85)