test(SimPinFeederTest): attempt to address test flakiness due to timeout (again)
This commit is an improvement of 6946b977ec59578ce44ed63ea627e25ba688caf1.

org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in com.github.iusmac.sevensim.telephony.SimPinFeederTest was not fulfilled within 3 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
	at com.github.iusmac.sevensim.telephony.SimPinFeederTest.assertTaskTimedOut(SimPinFeederTest.java:888)
	at com.github.iusmac.sevensim.telephony.SimPinFeederTest.test_ShouldFinishAfterExceedingFixedWaitTimeoutForSimStatusChangeEventWhenAvailableSimCardsDoNotRequirePin(SimPinFeederTest.java:217)

Signed-off-by: iusmac <iusico.maxim@libero.it>