feat: adapt to Android 16 (#75)
* Bump `targetSdk/compileSdk/buildToolsVersion` to `36`

* Import `android-36.jar` prebuilt

* fixup! Import `android-36.jar` prebuilt

* Fix testing with Robolectric/Roborazzi

Support for Android 16 (Baklava).

* Update golden screenshots for Roborazzi tests

* Bump SettingsLib to `android-16.0.0_r1` (2025-09 ASB patches)

* SettingsLib: introduce `Flags.isExpressiveDesignEnabled()` API

Added Flags package causing "undefined symbols" errors, which can only
be generated during AOSP build by aconfig tools.

---

e: file:///home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/SettingsTheme/src/com/android/settingslib/widget/SettingsThemeHelper.kt:21:45 Unresolved reference 'flags'.

* SettingsLib/BannerMessagePreference: add Kotlin plugin to compile `.kt` files

/home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/BannerMessagePreference.java:140: error: package ResolutionAnimator does not exist
    @Nullable private ResolutionAnimator.Data mResolutionData;
                                        ^
/home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/BannerMessagePreference.java:535: error: cannot find symbol
            @NonNull ResolutionCompletedCallback onCompletionCallback) {
                     ^
  symbol:   class ResolutionCompletedCallback
  location: class BannerMessagePreference
/home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/BannerMessagePreference.java:320: error: cannot find symbol
            new ResolutionAnimator(mResolutionData, holder).startResolutionAnimation();
                ^
  symbol:   class ResolutionAnimator
  location: class BannerMessagePreference
/home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/BannerMessagePreference.java:539: error: package ResolutionAnimator does not exist
        ResolutionAnimator.Data resolutionData =
                          ^
/home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/BannerMessagePreference.java:540: error: package ResolutionAnimator does not exist
                new ResolutionAnimator.Data(resolutionMessage, onCompletionCallback);

* SettingsLib: add `ButtonPreference` library

e: file:///home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/BannerMessagePreferenceGroup.kt:39:35 Unresolved reference 'NumberButtonPreference'.
e: file:///home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/BannerMessagePreferenceGroup.kt:40:37 Unresolved reference 'SectionButtonPreference'.
e: file:///home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/BannerMessagePreferenceGroup.kt:50:31 Unresolved reference 'btnContentDescription'.

* SettingsLib/BannerMessagePreference: resolve accessing hidden APIs

e: file:///home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/ResolutionAnimator.kt:23:25 Unresolved reference 'DeviceConfig'.
e: file:///home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/ResolutionAnimator.kt:173:25 Unresolved reference 'DeviceConfig'.

* SettingsLib/BannerMessagePreference: fix compilation error

/home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/BannerMessagePreference/src/com/android/settingslib/widget/BannerMessagePreference.java:47: error: package com.google.android.material.button does not exist
import com.google.android.material.button.MaterialButton;
                                         ^

* Use the framework list item height in expressive theme

The SettingsTheme overrides listPreferredItemHeightSmall with a bigger
value (@dimen/settingslib_expressive_space_large3=72dip vs. 48dip) when
using expressive theme, which is unnecessary as it's just looks odd
(e.g., in dropdown menu) and also breaks our screenshot tests.

* CollapsingToolbarBaseActivity: fix AppBarLayout being collapsed with expressive theme

AOSP devs decided to set com.google.android.material.R.styleable#AppBarLayout_expanded to "false"
in Android 16 when expressive theme is enabled.

We don't want that, and this behavior change breaks our screenshot
tests.
NOTE: the expanded state is applied only during the first launch before
the activity is laid out. The state will be retained upon activity
recreation (e.g., screen rotation).

* Revert "SettingsTheme/CollapsableTextView: fix Kotlin compilation errors"

This reverts commit ce1c068ea0928e04b8c5f8a060cb20ce65bab6fb.

No more compilation issues after bumping Kotlin from v1.9 to v2.1

Signed-off-by: iusmac <iusico.maxim@libero.it>

* SettingsLib(fetch.sh): fix patching logic

Handle the case when there are no .patch files to apply (the array will
contain the glob pattern).

* [Expressive design] Convert `PreferenceFragmentCompat` -> `SettingsBasePreferenceFragment`

Applies expressive design to preferences (also on groups & categories).

* [Expressive design] Update schedule card background color

Our schedule cards are custom preferences, so need apply the new
material colors from SettingsLib library when expressive design is
enabled.
---
@color/settingslib_materialColorSurfaceBright (collapsed)
@color/settingslib_materialColorSurfaceDim (expanded)

* [Expressive design] CollapsingToolbarBaseActivity: Do not enforce header content scrim background color

Inherit the color from expressive design theme.

* ToolbarDecorator: Include Toolbar's margins in the collapsed subtitle

* ToolbarDecorator: support auto-adjustable collapsing toolbar height when expanded

This removes the max 3 lines limit on the subtitle. It also improves the
way the toolbar title will position itself within the toolbar view, as
its gravity is set by the library to be at the bottom of the
CollapsingToolbarLayout, but we may have a subtitle at the very bottom
that also requires room, so they will overlap if the title is not pushed
up using setExpandedTitleMarginBottom() so that it's above the subtitle.

To work around the above, we continue to push the title to be above the
subtitle, but we also increase or shrink the overall height of the
CollapsingToolbarLayout, so that the title stays in the expanded area
and not behind the scrim.

* SchedulerActivityTest: increase height when testing on extra-small screens

Needed to fit the content of the CollapsingToolbarLayout, so that it's
visible on the screenshot.

* Update golden screenshots for Roborazzi tests

* [Expressive theme] CollapsingToolbarBaseActivity: hide the action button by default

Expressive theme adds an action button between framework Toolbar and
tree-dots/options button, that even when hidden (visibility = GONE),
leaves some empty space, which prevents the toolbar title/subtitle to
fully expand. The space comes from the action button's parent
view that has a padding on it.

To mitigate the empty space, we'll also hide the action button parent
view.

* Update golden screenshots for Roborazzi tests

* Bump AndroidX test libraries

* Bump `Error Prone` to `v2.42.0`

* Bump `Mockito` to `v5.20.0`

* Resolve `Error Prone` warnings

/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/ui/components/toolbar/ToolbarDecorator.java:390: warning: [EffectivelyPrivate] This declaration has public or protected modifiers, but is effectively private.
        public CollapsedSubtitle(final Context context) {
               ^
    (see https://errorprone.info/bugpattern/EffectivelyPrivate)
  Did you mean 'CollapsedSubtitle(final Context context) {'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/ui/components/toolbar/ToolbarDecorator.java:447: warning: [EffectivelyPrivate] This declaration has public or protected modifiers, but is effectively private.
        public ExpandedSubtitle(final Context context) {
               ^
    (see https://errorprone.info/bugpattern/EffectivelyPrivate)
  Did you mean 'ExpandedSubtitle(final Context context) {'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/ui/scheduler/SchedulerFragment.java:820: warning: [EffectivelyPrivate] This declaration has public or protected modifiers, but is effectively private.
        public LayoutManager(final Context context) {
               ^
    (see https://errorprone.info/bugpattern/EffectivelyPrivate)
  Did you mean 'LayoutManager(final Context context) {'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/UserAuthenticationObserverService.java:219: warning: [EffectivelyPrivate] This declaration has public or protected modifiers, but is effectively private.
        public Worker() {
               ^
    (see https://errorprone.info/bugpattern/EffectivelyPrivate)
  Did you mean 'Worker() {'?

* Bump AndroidX libraries to `android-16.0.0_r1` (2025-09 ASB patches)

---------

Signed-off-by: iusmac <iusico.maxim@libero.it>