test(SimPinFeederTest): attempt to address test flakiness due to timeout (#41)
This occurs only on 'release' builds... presumably because of bytecode
optimizations, which reduces overall execution time. To address this,
we'll allow a max. discrepancy of 250ms.

org.awaitility.core.ConditionTimeoutException: Condition was evaluated in 2 seconds 958 milliseconds which is earlier than expected minimum timeout 3 seconds
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:172)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
	at com.github.iusmac.sevensim.telephony.SimPinFeederTest.assertTaskTimedOut(SimPinFeederTest.java:906)
	at com.github.iusmac.sevensim.telephony.SimPinFeederTest.test_ShouldFinishAfterExceedingFixedWaitTimeoutForSimStatusChangeEventWhenAvailableSimCardsDoNotRequirePin(SimPinFeederTest.java:219)

Signed-off-by: iusmac <iusico.maxim@libero.it>