test(SimListActivityTest): address test timeout due unhandled exception in activity worker
Some tests are missing the call to waitActivityWorkerThreadUntilIdle()
after completion. To cover them all, we'll always drain the activity
worker thread after test completion. Similar fix has already been done
in 78117dab948818e5e048b83457cac7b7a9b91c84.

java.util.concurrent.TimeoutException: Waited for the worker thread Looper (SimListActivityViewModelThread, tid 1007) {4b5fe346} to become idle for 60 seconds. Most likely, an unhandled exception has occurred in the worker thread.
	at com.github.iusmac.sevensim.test.TestUtils.waitWorkerThreadLooperUntilIdle(TestUtils.java:291)
	at com.github.iusmac.sevensim.ui.sim.SimListActivityTestKt.waitActivityWorkerThreadUntilIdle(SimListActivityTest.kt:893)
	at com.github.iusmac.sevensim.ui.sim.SimListActivityTestKt.access$waitActivityWorkerThreadUntilIdle(SimListActivityTest.kt:1)
	at com.github.iusmac.sevensim.ui.sim.SimListActivityTest$SimEntries.test_should_disable_toggle_switch_on_click$lambda$14(SimListActivityTest.kt:530)
	at com.github.iusmac.sevensim.ui.sim.SimListActivityTestKt.onActivity(SimListActivityTest.kt:926)
	at com.github.iusmac.sevensim.ui.sim.SimListActivityTestKt.onActivity$default(SimListActivityTest.kt:868)
	at com.github.iusmac.sevensim.ui.sim.SimListActivityTest$SimEntries.test should disable toggle switch on click(SimListActivityTest.kt:528)

---

Exception in thread "SimListActivityViewModelThread" java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1103)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:716)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:399)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:920)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:860)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:252)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:301)
	at androidx.room.driver.SupportSQLiteStatement$SupportAndroidSQLiteStatement.step(SupportSQLiteStatement.android.kt:183)
	at com.github.iusmac.sevensim.scheduler.SubscriptionSchedulesDao_Impl.lambda$findNearestByDayOfWeekAndTime$4(SubscriptionSchedulesDao_Impl.java:249)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1$invokeSuspend$$inlined$internalPerform$1.invokeSuspend(DBUtil.kt:68)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1$invokeSuspend$$inlined$internalPerform$1.invoke(DBUtil.kt)
	at androidx.room.driver.SupportSQLiteConnectionPool.useConnection(SupportSQLiteConnectionPool.android.kt:42)
	at androidx.room.RoomConnectionManager.useConnection(RoomConnectionManager.android.kt:126)
	at androidx.room.RoomDatabase.useConnection$room_runtime_release(RoomDatabase.android.kt:587)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performBlocking$1.invokeSuspend(DBUtil.android.kt:243)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at androidx.room.util.DBUtil__DBUtil_androidKt.performBlocking(DBUtil.android.kt:69)
	at androidx.room.util.DBUtil.performBlocking(Unknown Source)
	at com.github.iusmac.sevensim.scheduler.SubscriptionSchedulesDao_Impl.findNearestByDayOfWeekAndTime(SubscriptionSchedulesDao_Impl.java:221)
	at com.github.iusmac.sevensim.scheduler.SubscriptionScheduler.findNearestAfterDateTime(SubscriptionScheduler.java:161)
	at com.github.iusmac.sevensim.scheduler.SubscriptionSchedulerSummaryBuilder.buildNextUpcomingSubscriptionScheduleSummary(SubscriptionSchedulerSummaryBuilder.java:80)
	at com.github.iusmac.sevensim.ui.sim.SimListViewModel.refreshSimEntries(SimListViewModel.java:82)
	at android.os.Handler.handleCallback(Handler.java:959)

Signed-off-by: iusmac <iusico.maxim@libero.it>