feat: adapt to Android 15 (#43)
* Gradle v8.10.2 + AGP v8.8

* Bumped kotlin plugin to the latest stable
* Migrated android.defaults.buildfeatures.buildconfig flag to build.gradle as requested:
    WARNING: The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.
      The current default is 'false'.
      It will be removed in version 10.0 of the Android Gradle plugin.
      To keep using this feature, add the following to your module-level build.gradle files:
          android.buildFeatures.buildConfig = true

* Set default `targetSdk` value at the project level

As per b/317358817, the com.android.settings plugin got support for
targetSdk with v8.8.0-alpha01.

* Set default `buildToolsVersion` value at the project level

Just noticed that this property was always available in the
com.android.settings plugin ;)

* Bump targetSdk/compileSdk/buildToolsVersion to 35

* Import `android-35.jar` prebuilt

* Bump SettingsLib to android-15.0.0_r10 tag (2025-01 ASB patches)

* Refactor SettingsLibLayoutPreference

- The 'lintOptions' was deprecated along time ago in favor of 'lint'.
- The 'compileOptions' will be inherited from the project build gradle.
- Commonize the library source path, as has already been done w/ other libraries.

* Align SettingsLibSettingsTheme with the upstream changes

https://android.googlesource.com/platform/frameworks/base/+/6a2564663bcad02b758cff76593891378506812c
https://android.googlesource.com/platform/frameworks/base/+/62f02f7b6e81e6b58097f5f01bf387695dfb8987%5E%21

* Remove SettingsLibUtils

https://android.googlesource.com/platform/frameworks/base/+/cf410ec680b63e0f3fbbe234a45fbdcca863170f

* Align SettingsLibCollapsingToolbarBaseActivity with the upstream changes

https://android.googlesource.com/platform/frameworks/base/+/bddf1693eed2eb2561b53ad26419df43c89f8392%5E%21/#F0
https://android.googlesource.com/platform/frameworks/base/+/ba669dc923706c8c37a9783749721a9f9eb95bcc%5E%21/#F0

* Fix testing with Robolectric/Roborazzi

Support for Android V.

* TelephonyControllerTest: fix failing tests

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "android.telephony.SubscriptionInfo.getGroupUuid()" because "info" is null
	at com.github.iusmac.sevensim.telephony.TelephonyControllerTest.assertFutureDone(TelephonyControllerTest.java:879)
	at com.github.iusmac.sevensim.telephony.TelephonyControllerTest.test_setSimState_ShouldPersistSubscriptionBeforeDisabling(TelephonyControllerTest.java:303)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluateSafely(JUnitSessionStore.java:55)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluate(JUnitSessionStore.java:43)
	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:108)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:502)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "android.telephony.SubscriptionInfo.getGroupUuid()" because "info" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.github.iusmac.sevensim.telephony.TelephonyControllerTest.assertFutureDone(TelephonyControllerTest.java:877)
	... 22 more
Caused by: java.lang.NullPointerException: Cannot invoke "android.telephony.SubscriptionInfo.getGroupUuid()" because "info" is null
	at android.telephony.SubscriptionManager.getSelectableSubscriptionInfoList(SubscriptionManager.java:3912)
	at android.telephony.SubscriptionManager.getSelectableSubscriptionInfoList(SubscriptionManager.java)
	at com.github.iusmac.sevensim.telephony.SubscriptionList.<init>(SubscriptionList.java:21)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy$1.<init>(SubscriptionsImplLegacy.java:90)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy.iterator(SubscriptionsImplLegacy.java:90)
	at com.github.iusmac.sevensim.telephony.Subscriptions.getSubscription(Subscriptions.java:178)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy.getSubscriptionForSimSlotIndex(SubscriptionsImplLegacy.java:137)
	at com.github.iusmac.sevensim.telephony.TelephonyControllerTest.lambda$test_setSimState_ShouldPersistSubscriptionBeforeDisabling$20(TelephonyControllerTest.java:304)
	... 4 more

* Remove `ShadowSubscriptionManagerOnSubscriptionsChangedListener`

Should be removed as per TODO, the android-all-robolectric.jar has been
updated. Tests pass.

* SchedulerActivityTest/SimListActivityTest: fix ShadowSubscriptionManager.setAvailableSubscriptionInfos usages

java.lang.IllegalStateException: Looper thread that has died due to an uncaught exception
	at org.robolectric.shadows.ShadowPausedMessageQueue.checkQueueState(ShadowPausedMessageQueue.java:409)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:697)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:104)
	at org.robolectric.shadows.ShadowPausedLooper.idleFor(ShadowPausedLooper.java:113)
	at org.robolectric.shadows.ShadowLooper.idleFor(ShadowLooper.java:223)
	at org.robolectric.shadows.ShadowPausedLooper.runToNextTask(ShadowPausedLooper.java:194)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$Activity$test should debounce subscription change events when sent in bursts$1.invoke(SchedulerActivityTest.kt:242)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$Activity$test should debounce subscription change events when sent in bursts$1.invoke(SchedulerActivityTest.kt:227)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTestKt.onActivity(SchedulerActivityTest.kt:3894)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTestKt.onActivity$default(SchedulerActivityTest.kt:3761)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$Activity.test should debounce subscription change events when sent in bursts(SchedulerActivityTest.kt:227)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluateSafely(JUnitSessionStore.java:55)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluate(JUnitSessionStore.java:43)
	at com.github.takahirom.roborazzi.RoborazziRule$runTest$evaluate$1.invoke(RoborazziRule.kt:208)
	at com.github.takahirom.roborazzi.RoborazziRule$runTest$evaluate$1.invoke(RoborazziRule.kt:203)
	at com.github.takahirom.roborazzi.RoborazziRule.runTest(RoborazziRule.kt:238)
	at com.github.takahirom.roborazzi.RoborazziRule.access$runTest(RoborazziRule.kt:27)
	at com.github.takahirom.roborazzi.RoborazziRule$apply$1.evaluate(RoborazziRule.kt:186)
	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:108)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:502)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "android.telephony.SubscriptionInfo.getGroupUuid()" because "info" is null
	at android.telephony.SubscriptionManager.getSelectableSubscriptionInfoList(SubscriptionManager.java:3912)
	at com.github.iusmac.sevensim.telephony.SubscriptionList.<init>(SubscriptionList.java:21)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy$1.<init>(SubscriptionsImplLegacy.java:90)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy.iterator(SubscriptionsImplLegacy.java:90)
	at com.github.iusmac.sevensim.telephony.Subscriptions.getSubscription(Subscriptions.java:178)
	at com.github.iusmac.sevensim.telephony.Subscriptions.getSubscriptionForSubId(Subscriptions.java:195)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivity.lambda$onSubscriptionsChanged$3(SchedulerActivity.java:142)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowPausedLooper$LooperReflector$$Reflector4.loop(Unknown Source)
	at org.robolectric.shadows.ShadowPausedLooper.loop(ShadowPausedLooper.java:472)
	at android.os.Looper.loop(Looper.java)
	at android.os.HandlerThread.run(HandlerThread.java:85)

* Support recording "golden" screenshots to `tests/test/roborazzi` in CI

In the .github/scripts/post-build-with-gradle.sh script we copy the
tests/test/roborazzi directory containing golden screenshots, but they
are not updated during tests, only the "compare" screenshots in
build/outputs/roborazzi are updated.

Signed-off-by: iusmac <iusico.maxim@libero.it>

* Increase maxHeapSize to 6144m for tests

Signed-off-by: iusmac <iusico.maxim@libero.it>

* SchedulerActivityTest: fix `test should defer list update when currently animating` test

The test fails because we want to draw exactly one frame on a paused
Choreographer, but the commit https://github.com/robolectric/robolectric/commit/0d813b7ebaff90b82b96869173c3e445295025da
("Set the default Choreographer frame delay in Robolectric to 15 ms (60
fps)") introduced in Robolectric 4.15, now makes the Choreographer frame
delay to default to 15ms to approximate ~60fps instead of 1ms (1000fps).

Robolectric offers an API to retrieve the current Choreographer frame
delay, so we'll use that value instead of hardcoding it to advance the
clock.

--

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$ScheduleListManagement$test should defer list update when currently animating$1.invoke$lambda$2(SchedulerActivityTest.kt:3655)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2(ActivityScenario.java:794)
	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:804)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$ScheduleListManagement$test should defer list update when currently animating$1.invoke(SchedulerActivityTest.kt:3644)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$ScheduleListManagement$test should defer list update when currently animating$1.invoke(SchedulerActivityTest.kt:3637)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTestKt.onActivity(SchedulerActivityTest.kt:3899)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTestKt.onActivity$default(SchedulerActivityTest.kt:3766)
	at com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest$ScheduleListManagement.test should defer list update when currently animating(SchedulerActivityTest.kt:3637)

Signed-off-by: iusmac <iusico.maxim@libero.it>

* SchedulerFragment: fix `test full view in landscape` tests

Since Android V, there's an extra "intermediate" layout step, which
force-enables AppBarLayout expansion animations. That fails the tests in
landscape, because, initially (when activity is first displayed), we
expect no AppBarLayout animations during layout. So, partial animations
are captured in the screenshots, making the tests to be very flaky.

Since we know our RecyclerView's adapter will *always* contain at least
one item (empty view or a schedule view), we can safely skip adjusting
AppBarLayout expansion during that intermediate state when no items are
present.

---

androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape.png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape_compare.png
Caused by: java.lang.AssertionError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape.png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape_compare.png
androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[31].png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[31]_compare.png
Caused by: java.lang.AssertionError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[31].png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[31]_compare.png
androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[32].png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[32]_compare.png
Caused by: java.lang.AssertionError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[32].png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[32]_compare.png
androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[33].png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[33]_compare.png
Caused by: java.lang.AssertionError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[33].png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[33]_compare.png
androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[34].png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[34]_compare.png
Caused by: java.lang.AssertionError: Roborazzi: /home/runner/work/7SIM/7SIM/tests/test/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[34].png is changed.
See the compare image at /home/runner/work/7SIM/7SIM/build/outputs/roborazzi/com.github.iusmac.sevensim.ui.scheduler.SchedulerActivityTest/Activity/test full view in landscape[34]_compare.png

Signed-off-by: iusmac <iusico.maxim@libero.it>

* Update golden screenshots for Roborazzi tests

Signed-off-by: iusmac <iusico.maxim@libero.it>

* QsAppLauncherTileService: explicitly suppress lint deprecation

/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/launcher/QsAppLauncherTileService.java:59: Error: TileService#startActivityAndCollapse(Intent) is deprecated. Use TileService#startActivityAndCollapse(PendingIntent) instead. [StartActivityAndCollapseDeprecated]
            service.startActivityAndCollapse(intent);
                                             ~~~~~~

   Explanation for issues of type "StartActivityAndCollapseDeprecated":
   TileService#startActivityAndCollapse(Intent) has been deprecated, and will
   throw an UnsupportedOperationException if used in apps targeting Android
   versions UpsideDownCake and higher. Convert the Intent to a PendingIntent.

Signed-off-by: iusmac <iusico.maxim@libero.it>

* Update README.md

Signed-off-by: iusmac <iusico.maxim@libero.it>

---------

Signed-off-by: iusmac <iusico.maxim@libero.it>