Merge December 2025 QPR2 Patches (android-16.0.0_r4) (#91)
* SettingsLib: bump to `android-16.0.0_r4` tag

* SettingsLib: bump `minSdk` version to 23

https://android.googlesource.com/platform/frameworks/base/+/40ba4786d08b0618fe77ce7435116dbd41f2fb12 ("Update SettingsLib/DataStore min_sdk_version to 23.")

* CollapsingToolbarBaseActivity: add APIs for action button

https://android.googlesource.com/platform/frameworks/base/+/7e207744232a1a9f22ba6edafe26d0e575290090 ("Added button in CollapsingToolbar")

* CollapsingToolbarBaseActivity: add APIs for trailing buttons (primary/secondary/action)

https://android.googlesource.com/platform/frameworks/base/+/5deb69739d62f225dd8ba15f0987250d107a1145 ("[Expressive design] Add trailing buttons to CollapsingToolbar")

* CollapsingToolbarBaseActivity: add API to toggle Toolbar trailing buttons

Now we have a trailing buttons view holding the action, primary &
secondary buttons not just the action button, so refactoring is needed.

* CollapsingToolbarBaseActivity: collapse toolbar when hosting multiple fragments

https://android.googlesource.com/platform/frameworks/base/+/e0bf8cb02e2bbab0dea2ec1d1153b1b8818b6677 ("Collapse toolbar when hosting multiple fragments")

* SettingsLib/CollapsingToolbarBaseActivity: fix compilation issues

* ScrollableToolbarItemLayout is a Kotlin class.

---

/home/runner/work/7SIM/7SIM/SettingsLib/fwb/packages/SettingsLib/CollapsingToolbarBaseActivity/src/com/android/settingslib/collapsingtoolbar/CollapsingToolbarBaseActivity.java:34: error: cannot find symbol
import com.android.settingslib.collapsingtoolbar.widget.ScrollableToolbarItemLayout;
                                                       ^
  symbol:   class ScrollableToolbarItemLayout
  location: package com.android.settingslib.collapsingtoolbar.widget

* Bump `Room` to `v2.8.0-alpha01` (`android-16.0.0_r4` tag)

* Bump `Material3` to `v1.14.0-alpha02` (`android-16.0.0_r4` tag)

* Bump AndroidX deps to `android-16.0.0_r4` tag

* CollapsingToolbarBaseActivity: fix compilations errors

/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/ui/components/CollapsingToolbarBaseActivity.java:87: error: cannot find symbol
                  .map((v) -> (View) v.getParent());
                                      ^
symbol:   method getParent()
location: variable v of type Object

* SimPinFeederTest: increase task timeout in CI environment to 5 seconds

GitHub Actions runners are very slow sometimes, which timeouts our
tests, probably due to JVM waiting for resources from the OS such as
processor. We already faced a similar issue in
1b353b00c1b66a49fc27affbbd3b4eeb2909bfe7 and 6946b977ec59578ce44ed63ea627e25ba688caf1, so increasing timeout a bit should resolve the
issue. To maintain speed when testing locally, we still want to timeout
after 3 seconds.

    org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in com.github.iusmac.sevensim.telephony.SimPinFeederTest was not fulfilled within 3 seconds.
            at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
            at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
            at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
            at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1160)
            at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1129)
            at com.github.iusmac.sevensim.telephony.SimPinFeederTest.assertTaskInState(SimPinFeederTest.java:879)
            at com.github.iusmac.sevensim.telephony.SimPinFeederTest.test_ShouldUnlockWhenAttemptsRemainingIsAtLeastThree_SinceS(SimPinFeederTest.java:274)

---

Another symptom that GitHub Actions runners are very slow, is that we
even got a NPE in the SimPinFeeder thread that runs in parallel, because
the main/test thread already terminated (due to a fixed timeout), and
recycled objects that aren't reachable anymore.

    Exception in thread "Thread-71" java.lang.NullPointerException: Cannot invoke "android.telephony.TelephonyManager.getSimState()" because "this.mTelephonyManager" is null
            at com.github.iusmac.sevensim.telephony.SimPinFeeder$SimCard.toString(SimPinFeeder.java:325)
            at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3158)
            at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3036)
            at java.base/java.util.Formatter.format(Formatter.java:2791)
            at java.base/java.util.Formatter.format(Formatter.java:2728)
            at java.base/java.lang.String.format(String.java:4431)
            at com.github.iusmac.sevensim.Logger.format(Logger.java:112)
            at com.github.iusmac.sevensim.Logger.v(Logger.java:56)
            at com.github.iusmac.sevensim.telephony.SimPinFeeder.run(SimPinFeeder.java:99)

* SimPinFeederTest: fix compilation errors

/home/runner/work/7SIM/7SIM/tests/test/java/com/github/iusmac/sevensim/telephony/SimPinFeederTest.java:120: error: element value must be a constant expression
    @Test(timeout = TASK_WAIT_TIMEOUT_MILLIS)

* Revert "fix(ui/PrimarySwitchPreference): address extra divider empty space [Expressive Design] (#79)"

This reverts commit 60c51647e439e22d10c2e50144e798e02580abe7.

* fix(ui/PrimarySwitchPreference): address extra divider empty space [Expressive Design]

In the expressive theme introduced in Android 16 (Baklava), the switch
preference used in the SIM list activity contains additional space at
the beginning of the parent layout causing the title (e.g., SIM name)
and summary (e.g., next upcoming schedule) text views that precede it to
wrap earlier.

* Update golden screenshots for Roborazzi tests