Downgrade AGP to `v8.11.2`
The tests fail because our static BroadcastReceiver (AlarmReceiver)
is not listed anymore in ShadowApplication.getRegisteredReceivers().

    java.util.NoSuchElementException: No value present
            at java.base/java.util.Optional.get(Optional.java:143)
            at com.github.iusmac.sevensim.scheduler.AlarmReceiverTest.setUp(AlarmReceiverTest.java:97)

After manual investigation, it seems that Robolectric can't load static
<receiver> components from our AndroidManifest.xml file starting from
AGP 8.12 or newer.