build(deps): bump Gradle and update deps (#93)
* Bump Gradle to `v8.14.3`

* Bump AGP plugin to `v8.13.2`

* Extract AGP version from Toml file for `com.android.settings` plugin

Unfortunately, we cannot use "alias()" in the "plugins {}" block to
reuse the AGP version from gradle/libs.versions.toml file. Getting an
error instead (happens only in settings.gradle script):

    only alias(libs.plugins.someAlias) plugin identifiers where libs is a valid version catalog

* Suppress false positive `GradlePluginVersion` lint check

/home/runner/work/7SIM/7SIM/settings.gradle:22: Error: You must use a newer version of the Android Gradle plugin. The minimum supported version is 4.0.0 and the recommended version is 8.13.2 [GradlePluginVersion]
    id 'com.android.settings' version "${apgVersion}"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "GradlePluginVersion":
   Not all versions of the Android Gradle plugin are compatible with all
   versions of the SDK. If you update your tools, or if you are trying to open
   a project that was built with an old version of the tools, you may need to
   update your plugin version number.

* Bump Roborazzi to `v1.54.0`

* Downgrade AGP to `v8.11.2`

The tests fail because our static BroadcastReceiver (AlarmReceiver)
is not listed anymore in ShadowApplication.getRegisteredReceivers().

    java.util.NoSuchElementException: No value present
            at java.base/java.util.Optional.get(Optional.java:143)
            at com.github.iusmac.sevensim.scheduler.AlarmReceiverTest.setUp(AlarmReceiverTest.java:97)

After manual investigation, it seems that Robolectric can't load static
<receiver> components from our AndroidManifest.xml file starting from
AGP 8.12 or newer.

* Fix typo in `settings.gradle`

* Bump Mockito to `v5.21.0`

* Bump Kover coverage library to `v0.9.4`

* Bump `Error Prone` library to `v2.45.0`

* Resolve `Error Prone` warnings/errors

/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/Logger.java:111: warning: [AnnotateFormatMethod] This method uses a pair of parameters as a format string and its arguments, but the enclosing method wasn't annotated. Doing so gives compile-time rather than run-time protection against malformed format strings.
    private static String format(String message, Object... args) {
                          ^
    (see https://errorprone.info/bugpattern/AnnotateFormatMethod)

/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/SystemBroadcastReceiver.java:51: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
        mLogger.d("onReceive() : intent=" + intent);
                 ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("onReceive() : intent=%s", intent);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/DirectBootAwareBroadcastReceiver.java:46: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
        mLogger.d("onReceive() : intent=" + intent);
                 ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("onReceive() : intent=%s", intent);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/Subscriptions.java:76: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.v("onReceive() : intent=" + intent);
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.v("onReceive() : intent=%s", intent);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/SubscriptionController.java:64: error: [FormatStringAnnotation] Local format string variables must only be assigned to compile time constant values. Invalid format string assignment: final String logPrefix = String.format(Locale.getDefault(), "setUiccApplicationsEnabled(subId=%d,enabled=%s)", subId, enabled)
        mLogger.d(logPrefix);
                 ^
    (see https://errorprone.info/bugpattern/FormatStringAnnotation)
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/SubscriptionController.java:69: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.e(logPrefix + " Aborting due to missing subscription.");
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.e("%s Aborting due to missing subscription.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:116: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.w(logPrefix + "Aborting due to Airplane mode.");
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.w("%sAborting due to Airplane mode.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:125: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.d(logPrefix + "In sync block.");
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("%sIn sync block.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:131: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
                mLogger.e(logPrefix + "Aborting due to missing subscription.");
                         ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.e("%sAborting due to missing subscription.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:137: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
                mLogger.w(logPrefix + "Already in state.");
                         ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.w("%sAlready in state.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:202: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
                        mLogger.w(logPrefix + "Acquire wait interrupted.");
                                 ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.w("%sAcquire wait interrupted.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:297: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
                default -> mLogger.e(logPrefix + ". Unexpected resCode.");
                                    ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'default -> mLogger.e("%s. Unexpected resCode.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:359: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
        mLogger.d(logPrefix + ", requestFailed=%s,shouldNotifyAllListeners=%s", requestFailed,
                 ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("%s, requestFailed=%s,shouldNotifyAllListeners=%s", logPrefix, requestFailed, shouldNotifyAllListeners);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/ui/scheduler/SchedulerViewModel.java:428: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.d("onReceive() : intent=" + intent);
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("onReceive() : intent=%s", intent);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/ui/sim/SimListActivity.java:154: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.d("onReceive() : intent=" + intent);
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("onReceive() : intent=%s", intent);'?