feat(#15): adapt to Android 14.0 (#16)
* feat: update SettingsLib parts from android-14.0.0_r31

* All SettingsLib's parts are now shipped using a separate namespace in
  order to use resource processor.
* Enabled newly added 'use_resource_processor' clause in Android.bp to
  use Bazel's resource processor instead of aapt2 to generate R.class
  files. As per sources, this will be enabled by default in the future.
  The android.nonTransitiveRClass is the equivalent setting in AGP which
  is enabled by default since AGP 8, so we removed it.
  All in all, this speeds up compilation and reduces app size.

* chore: align Gradle dependencies with android-14.0.0_r31

* feat(SubscriptionsDao): switch to `@Upsert` added in Room v2.5.0-alpha03

* Also, convert the DAO back to interface while we're at it.

See https://developer.android.com/jetpack/androidx/releases/room#2.5.0-alpha03

* feat(telephony): switch to BundleCompat.getParcelable() impl

* Support was added in AndroidX Core v1.10.0

* fix(QsAppLauncherTileService): startActivityAndCollapse: Starting activity from TileService using an Intent is not allowed.

* --------- beginning of crash
    E  AndroidRuntime FATAL EXCEPTION: main
    E  AndroidRuntime Process: com.github.iusmac.sevensim, PID: 10791
    E  AndroidRuntime java.lang.UnsupportedOperationException: startActivityAndCollapse: Starting activity from TileService using an Intent is not allowed.
    E  AndroidRuntime    at android.service.quicksettings.TileService.startActivityAndCollapse(TileService.java:355)
    E  AndroidRuntime    at com.github.iusmac.sevensim.launcher.QsAppLauncherTileService.onClick(QsAppLauncherTileService.java:30)
    E  AndroidRuntime    at android.service.quicksettings.TileService$H.handleMessage(TileService.java:494)
    E  AndroidRuntime    at android.os.Handler.dispatchMessage(Handler.java:107)
    E  AndroidRuntime    at android.os.Looper.loopOnce(Looper.java:232)
    E  AndroidRuntime    at android.os.Looper.loop(Looper.java:317)
    E  AndroidRuntime    at android.app.ActivityThread.main(ActivityThread.java:8498)
    E  AndroidRuntime    at java.lang.reflect.Method.invoke(Native Method)
    E  AndroidRuntime    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    E  AndroidRuntime    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

* Also
    > Task :compileDebugJavaWithJavac
    Note:
    src/com/github/iusmac/sevensim/launcher/QsAppLauncherTileService.java uses or overrides a deprecated API.

* fix(NotificationManager): handle a potential SecurityException

/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/NotificationManager.java:87: Error: Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException [MissingPermission]

       mNotificationManagerCompat.notify(BACKGROUND_RESTRICTED_NOTIFICATION_ID, notification);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* chore(AndroidManifest): specify foreground service type for FGS to meed the U requirement

* fix(ApplicationInfo): un-deprecate PackageManager APIs that use int flags

See https://android.googlesource.com/platform/frameworks/base/+/15aa824757dc80d8e10775d77dbf2535be51cad8.

* chore: update README.md

Signed-off-by: iusmac <iusico.maxim@libero.it>

* fix: the resource @string/not_set is marked as private in androidx.preference:preference:1.2.0-alpha01

../../src/com/github/iusmac/sevensim/ui/components/TimePickerPreference.java:226: The resource @string/not_set is marked as private in androidx.preference:preference:1.2.0-alpha01
        public @Nullable CharSequence provideSummary(final @NonNull TimePickerPreference preference) {
            final CharSequence time = preference.getTime();
            return time != null ? time :
                preference.getContext().getString(androidx.preference.R.string.not_set);
        }
    }
}

Signed-off-by: iusmac <iusico.maxim@libero.it>

---------

Signed-off-by: iusmac <iusico.maxim@libero.it>