QsAppLauncherTileService: explicitly suppress lint deprecation
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/launcher/QsAppLauncherTileService.java:59: Error: TileService#startActivityAndCollapse(Intent) is deprecated. Use TileService#startActivityAndCollapse(PendingIntent) instead. [StartActivityAndCollapseDeprecated]
            service.startActivityAndCollapse(intent);
                                             ~~~~~~

   Explanation for issues of type "StartActivityAndCollapseDeprecated":
   TileService#startActivityAndCollapse(Intent) has been deprecated, and will
   throw an UnsupportedOperationException if used in apps targeting Android
   versions UpsideDownCake and higher. Convert the Intent to a PendingIntent.

Signed-off-by: iusmac <iusico.maxim@libero.it>