TelephonyControllerTest: fix failing tests
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "android.telephony.SubscriptionInfo.getGroupUuid()" because "info" is null
	at com.github.iusmac.sevensim.telephony.TelephonyControllerTest.assertFutureDone(TelephonyControllerTest.java:879)
	at com.github.iusmac.sevensim.telephony.TelephonyControllerTest.test_setSimState_ShouldPersistSubscriptionBeforeDisabling(TelephonyControllerTest.java:303)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluateSafely(JUnitSessionStore.java:55)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluate(JUnitSessionStore.java:43)
	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:108)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:502)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "android.telephony.SubscriptionInfo.getGroupUuid()" because "info" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.github.iusmac.sevensim.telephony.TelephonyControllerTest.assertFutureDone(TelephonyControllerTest.java:877)
	... 22 more
Caused by: java.lang.NullPointerException: Cannot invoke "android.telephony.SubscriptionInfo.getGroupUuid()" because "info" is null
	at android.telephony.SubscriptionManager.getSelectableSubscriptionInfoList(SubscriptionManager.java:3912)
	at android.telephony.SubscriptionManager.getSelectableSubscriptionInfoList(SubscriptionManager.java)
	at com.github.iusmac.sevensim.telephony.SubscriptionList.<init>(SubscriptionList.java:21)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy$1.<init>(SubscriptionsImplLegacy.java:90)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy.iterator(SubscriptionsImplLegacy.java:90)
	at com.github.iusmac.sevensim.telephony.Subscriptions.getSubscription(Subscriptions.java:178)
	at com.github.iusmac.sevensim.telephony.SubscriptionsImplLegacy.getSubscriptionForSimSlotIndex(SubscriptionsImplLegacy.java:137)
	at com.github.iusmac.sevensim.telephony.TelephonyControllerTest.lambda$test_setSimState_ShouldPersistSubscriptionBeforeDisabling$20(TelephonyControllerTest.java:304)
	... 4 more