Resolve `Error Prone` warnings/errors
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/Logger.java:111: warning: [AnnotateFormatMethod] This method uses a pair of parameters as a format string and its arguments, but the enclosing method wasn't annotated. Doing so gives compile-time rather than run-time protection against malformed format strings.
    private static String format(String message, Object... args) {
                          ^
    (see https://errorprone.info/bugpattern/AnnotateFormatMethod)

/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/SystemBroadcastReceiver.java:51: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
        mLogger.d("onReceive() : intent=" + intent);
                 ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("onReceive() : intent=%s", intent);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/DirectBootAwareBroadcastReceiver.java:46: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
        mLogger.d("onReceive() : intent=" + intent);
                 ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("onReceive() : intent=%s", intent);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/Subscriptions.java:76: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.v("onReceive() : intent=" + intent);
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.v("onReceive() : intent=%s", intent);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/SubscriptionController.java:64: error: [FormatStringAnnotation] Local format string variables must only be assigned to compile time constant values. Invalid format string assignment: final String logPrefix = String.format(Locale.getDefault(), "setUiccApplicationsEnabled(subId=%d,enabled=%s)", subId, enabled)
        mLogger.d(logPrefix);
                 ^
    (see https://errorprone.info/bugpattern/FormatStringAnnotation)
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/SubscriptionController.java:69: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.e(logPrefix + " Aborting due to missing subscription.");
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.e("%s Aborting due to missing subscription.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:116: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.w(logPrefix + "Aborting due to Airplane mode.");
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.w("%sAborting due to Airplane mode.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:125: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.d(logPrefix + "In sync block.");
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("%sIn sync block.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:131: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
                mLogger.e(logPrefix + "Aborting due to missing subscription.");
                         ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.e("%sAborting due to missing subscription.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:137: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
                mLogger.w(logPrefix + "Already in state.");
                         ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.w("%sAlready in state.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:202: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
                        mLogger.w(logPrefix + "Acquire wait interrupted.");
                                 ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.w("%sAcquire wait interrupted.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:297: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
                default -> mLogger.e(logPrefix + ". Unexpected resCode.");
                                    ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'default -> mLogger.e("%s. Unexpected resCode.", logPrefix);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/telephony/TelephonyController.java:359: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
        mLogger.d(logPrefix + ", requestFailed=%s,shouldNotifyAllListeners=%s", requestFailed,
                 ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("%s, requestFailed=%s,shouldNotifyAllListeners=%s", logPrefix, requestFailed, shouldNotifyAllListeners);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/ui/scheduler/SchedulerViewModel.java:428: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.d("onReceive() : intent=" + intent);
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("onReceive() : intent=%s", intent);'?
/home/runner/work/7SIM/7SIM/src/com/github/iusmac/sevensim/ui/sim/SimListActivity.java:154: warning: [FormatStringShouldUsePlaceholders] Using a format string avoids string concatenation in the common case.
            mLogger.d("onReceive() : intent=" + intent);
                     ^
    (see https://errorprone.info/bugpattern/FormatStringShouldUsePlaceholders)
  Did you mean 'mLogger.d("onReceive() : intent=%s", intent);'?