SimPinFeederTest: increase task timeout in CI environment to 5 seconds
GitHub Actions runners are very slow sometimes, which timeouts our
tests, probably due to JVM waiting for resources from the OS such as
processor. We already faced a similar issue in
1b353b00c1b66a49fc27affbbd3b4eeb2909bfe7 and 6946b977ec59578ce44ed63ea627e25ba688caf1, so increasing timeout a bit should resolve the
issue. To maintain speed when testing locally, we still want to timeout
after 3 seconds.

    org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in com.github.iusmac.sevensim.telephony.SimPinFeederTest was not fulfilled within 3 seconds.
            at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
            at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
            at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
            at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1160)
            at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1129)
            at com.github.iusmac.sevensim.telephony.SimPinFeederTest.assertTaskInState(SimPinFeederTest.java:879)
            at com.github.iusmac.sevensim.telephony.SimPinFeederTest.test_ShouldUnlockWhenAttemptsRemainingIsAtLeastThree_SinceS(SimPinFeederTest.java:274)

---

Another symptom that GitHub Actions runners are very slow, is that we
even got a NPE in the SimPinFeeder thread that runs in parallel, because
the main/test thread already terminated (due to a fixed timeout), and
recycled objects that aren't reachable anymore.

    Exception in thread "Thread-71" java.lang.NullPointerException: Cannot invoke "android.telephony.TelephonyManager.getSimState()" because "this.mTelephonyManager" is null
            at com.github.iusmac.sevensim.telephony.SimPinFeeder$SimCard.toString(SimPinFeeder.java:325)
            at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3158)
            at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3036)
            at java.base/java.util.Formatter.format(Formatter.java:2791)
            at java.base/java.util.Formatter.format(Formatter.java:2728)
            at java.base/java.lang.String.format(String.java:4431)
            at com.github.iusmac.sevensim.Logger.format(Logger.java:112)
            at com.github.iusmac.sevensim.Logger.v(Logger.java:56)
            at com.github.iusmac.sevensim.telephony.SimPinFeeder.run(SimPinFeeder.java:99)